baseURL: http://vigilo.city/
languageCode: fr-FR
defaultContentLanguage: fr
title: Site web application Vigilo
theme: hugo-theme-learn
themesdir: themes/
metaDataFormat: yaml
defaultContentLanguageInSubdir: true
publishDir: "docs"

params:
  editURL: 'https://github.com/jesuisundesdeux/vigilo-website/edit/master/content/'
  description: Site web de l'application Vigilo
  author: JeSuisUnDesDeux
  showVisitedLinks: true
  disableBreadcrumb: false
  disableNextPrev: false
outputs:
  home:
    - HTML
    - RSS
    - JSON
Languages:
  fr:
    title: Site web Vigilo
    weight: 1
    languageName: Français
    menu:
      shortcuts:
        - name: <i class='fab fa-fw fa-android'></i> Application Android
          url: >-
            https://play.google.com/store/apps/details?id=com.velocite34.vigilo&hl=fr
          weight: 10
        - name: <i class='fas fa-fw fa-city'></i> Villes
          url: /fr/villes/
          weight: 11
  en:
    title: Vigilo website
    weight: 2
    languageName: English
    menu:
      shortcuts:
        - name: <i class='fab fa-fw fa-android'></i> Application Android
          url: >-
            https://play.google.com/store/apps/details?id=com.velocite34.vigilo&hl=fr
          weight: 10